### ISSUE TITLE
Character separation not working

### ISSUE THREAD

**Issue by yashkan27** [ikergarcia1996/Handwritten-Names-Recognition#4]
Hi,

I am following your code and it is working good on your data. 
Now I am trying to fit the model on my custom data. I have changed the template and the image and passing the cropped image to the `get_characters()` function, it is showing a single character.
Please suggests if I am missing something.

**Comment by ikergarcia1996** [comment]
Hi!
The function to extract characters was written specifically for the "Transcriptions of names from handwriting dataset" from Data for Everyone. If I remember correctly, we used pattern matching to find the machine written "OM:" letters to locate where the handwritten names start and then extract the characters. If you want to use the model with custom data you will need to rewrite the function to fit your data.

**Comment by yashkan27** [comment]
Thanks for the quick reply.
From what I understand is, I to change the internal cropping mechanism also along with the new template image. 
Also, can you tell me how to deal with underlines? Because I think that line is causing a problem for feature extraction from the image.
Again thanks for the repo and it is showing very good results on your dataset.
